version: 2
jobs:
  build:
    working_directory: ~/django-labs-accounts
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip tox coveralls
      - run:
          name: Run tests
          command: |
            tox
            coveralls

workflows:
  version: 2
  build:
    jobs:
      - build